### ISSUE TITLE
External resources

### ISSUE THREAD

**Issue by cjessett** [Aaron-Day/BWS-Dasmotos#1]
(Important) [Here](https://github.com/Aaron-Day/BWS-Dasmotos/blob/4e930555f4ce12002004b7d468679bedf1b7a3ea/DasmotosArtsCrafts/index.html#L11) you should include the image with the project and reference it locally. Since URLs can break or change instead of linking to external resources we include everything with the project.

**Comment by Aaron-Day** [comment]
Added images folder with images and refactored links to the appropriate relative address.
