### ISSUE TITLE
id attribute

### ISSUE THREAD

**Issue by cjessett** [Aaron-Day/BWS-Dasmotos#3]
(Subtlety) [Here](https://github.com/Aaron-Day/BWS-Dasmotos/blob/4e930555f4ce12002004b7d468679bedf1b7a3ea/DasmotosArtsCrafts/resources/css/styles.css#L19) and below it would be more appropriate to use the `id` attribute instead of the `class`. Just use a `#` instead of a `.` in your css and use the `id` attribute in your HTML. Since these styles are each only applied to a single element, the `id` attribute is perfect.

**Comment by Aaron-Day** [comment]
Changed appropriate class attributes to id attributes; refactored css stylesheet accordingly.
